### ISSUE TITLE
month is invisible in dark mode

### ISSUE THREAD

**Issue by tisdall** [leejarvis/phoenix-calendar-component.ex#1]
I was looking at [the demo](https://leejarvis.me/posts/2024/phoenix-calendar-component) and was thinking it was weird that there was no month, but then realized it's actually there with the exact same colour as the background.

<img width="717" alt="calendar screen shot" src="https://github.com/user-attachments/assets/549e6776-7f96-48d6-974c-5d310fe1cee4">

Highlighting the month text:
<img width="709" alt="month highlighted" src="https://github.com/user-attachments/assets/2c8639ed-bec7-4921-aed0-fcbaf22a5468">

**Comment by leejarvis** [comment]
Thanks for reporting! I have adjusted the calendar styles on the demo to account for dark mode 💜
